apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-db-backup
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          volumes:
            - name: gcp-key
              secret:
                secretName: gcs-backup-key
                items:
                  - key: dwk-gke-479716-839a54b0c0dc.json
                    path: gcs-key.json
          containers:
            - name: todo-db-backup
              image: PROJECT/BACKUP
              env:
                - name: URL
                  value: "postgres://postgres:postgres@postgres-svc:5432/postgres"
              volumeMounts:
                - name: gcp-key
                  mountPath: /var/secrets/google
              resources:
                requests:
                  cpu: "30m"
                  memory: "64Mi"
                limits:
                  cpu: "200m"
                  memory: "256Mi"
